### ISSUE TITLE
app-flickity with dom-repeat not working

### ISSUE THREAD

**Issue by jobizzness** [ryanburns23/app-flickity#1]
Here is my code please take a look. Children are just stacked in a vertical column.

        
        <app-flickity hide-page-dots="true" id="flickity">
            <template is="dom-repeat" items="[[data]]">
                <div cell>
                    <div class="layout horizontal wrap" style="position: relative;">
                        <div class="collection_footer">
                            <p>30 Way TO Jump Off From The Tree While Making More Cash !</p>
                        </div>
                        <iron-image preload
                                    style="background-color: #eee; height: 250px; width: 100%;"
                                    fade
                                    sizing="cover" src="http://68.media.tumblr.com/233478dbea0b04623391e44fe8f7f132/tumblr_o7sp8s0C1k1qf87x2o1_1280.jpg"/>
                    </div>
                </div>
            </template>
        </app-flickity>

any idea ?

**Comment by ryanburns23** [comment]
@jobizzness  app-flickity calls init when it is attached. If your data takes some time to load in, you need the dom-repeat template to be fully rendered before init is called. 

`_this.$.flickity.destroy(); `
`_this.$.tm.render();`
`_this.$.flickity.init();` 

See this fiddle for an example of how to achieve this with the current state of app flickity: https://jsfiddle.net/m7r4yn3j/16/

I need to update the doc's to note this. 
I'll eventually add a disabled property so you can delay the init of flickity.

**Comment by jobizzness** [comment]
This worked thanks !
beforeRegister() {

        this.is = 'collection-slide';

        this.properties = {

            data : {
                type: Object,
                observer:'_reloadSlider'
            }
        }
    }

    _reloadSlider(){
            this.$.flickity.destroy();
        return this.$.flickity.init();
    }
